### ISSUE TITLE
How To Use

### ISSUE THREAD

**Issue by JaysonBayson** [MegaApuTurkUltra/ScratchTools#6]
**Hello**

I am trying to use the **Audio Visualizer Tool** but I can't figure out how to use it.
I know it's _silly_, but there are no tutorials I could find on the internet.
_I await your response._
![capture](https://user-images.githubusercontent.com/36285315/36007045-2a80c0d8-0d06-11e8-986d-48f9c9a10483.PNG)

**Comment by ghost** [comment]
If I remember (its been a while since I used this), you first have to create a empty scratch project and save it somewhere. _This is going to be your input_ (When you click on choose file, you pick the blank scratch file that you created earlier). **Then for your output, you want to use a .wav file THAT IS NOT CONVERTED BY SCRATCH** (What i mean by that, is that the file must be converted by (online wav converter **or** you don't need too if the file is already in wav form and ** is not converted by scratch**. For the fps settings, its your preference (i recommend 30). Finally you can decide if you want full spectrum (which is great for linear visualizers such as that monstercat visualizer format), or not (if you like the trap nation version).

**Comment by ghost** [comment]
if my explanation doesn't work, then try putting the wav file in input and the blank scratch project file in output (i forgot which is which)

**Comment by EpicEliteT** [comment]
close

**Comment by EpicEliteT** [comment]
close #6

**Comment by JaysonBayson** [comment]
It hasn't worked, _sorry_, here's the log when the audio is the input and the scratch project as the output file
(I called `Viz.sb2`)

```
Initializing...
==== JavaSound Minim Error ====
==== IOException: Resetting to invalid mark

java.lang.NullPointerException
	at ddf.minim.javasound.JSMinim.getAudioRecordingStream(Unknown Source)
	at ddf.minim.Minim.loadFileIntoBuffer(Unknown Source)
	at apu.scratch.tools.gen.visualizer.VisualizerGenMinim.toolMain(VisualizerGenMinim.java:62)
	at apu.scratch.tools.gen.visualizer.VisualizerGenMinim.call(VisualizerGenMinim.java:193)
	at apu.scratch.tools.ToolBase.callWithParams(ToolBase.java:69)
	at apu.scratch.tools.gui.ToolRunner.run(ToolRunner.java:27)
	at java.lang.Thread.run(Unknown Source)
Whoops, there was an error reading your sound file. If you haven't already, try using a WAV file, those tend to work better
```

Here's the log when the audio is the output and the scratch project as the input file
(I called `Viz.sb2`)

```
==== JavaSound Minim Error ====
==== IOException: Resetting to invalid mark

java.lang.NullPointerException
	at ddf.minim.javasound.JSMinim.getAudioRecordingStream(Unknown Source)
	at ddf.minim.Minim.loadFileIntoBuffer(Unknown Source)
	at apu.scratch.tools.gen.visualizer.VisualizerGenMinim.toolMain(VisualizerGenMinim.java:62)
	at apu.scratch.tools.gen.visualizer.VisualizerGenMinim.call(VisualizerGenMinim.java:193)
	at apu.scratch.tools.ToolBase.callWithParams(ToolBase.java:69)
	at apu.scratch.tools.gui.ToolRunner.run(ToolRunner.java:27)
	at java.lang.Thread.run(Unknown Source)
Whoops, there was an error reading your sound file. If you haven't already, try using a WAV file, those tend to work better
```

**Comment by ghost** [comment]
sorry for the extremely late reply, i haven't been on scratch or github, but it's definitely an audio issue: "Whoops, there was an error reading your sound file. If you haven't already, try using a WAV file, those tend to work better"
Make sure you are using a wav file that's not converted by scratch 
(edit: ehh i said that eariler..., I would test by taking an mp3, go to an online converter (mp3 to wav) and use that wav file)

**Comment by ghost** [comment]
I `DONT` UNDERSTAND THIS
